export default {
    WINDOW_DATA:             'WINDOW_DATA',
    SUBTRACT_LAST_NAME:      'SUBTRACT_LAST_NAME',
    ADD_NAME:                'ADD_NAME',
    ADD_NAME_DONE:           'ADD_NAME_DONE',
    ADD_NAME_FAIL:           'ADD_NAME_FAIL',
    SERVER_ERROR:            'SERVER_ERROR',
    NETWORK_ERROR:           'NETWORK_ERROR',
    CLEAR_SERVER_VALIDATION: 'CLEAR_SERVER_VALIDATION',
};
